# Generated by Django 5.1 on 2024-08-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_lahatra', '0006_alter_personne_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='guichet',
            name='nb_now',
            field=models.IntegerField(default=0),
        ),
    ]
