# Generated by Django 5.1 on 2024-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_lahatra', '0007_guichet_nb_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='guichet',
            name='nb_personne',
            field=models.IntegerField(default=0),
        ),
    ]
