# Generated by Django 5.1 on 2024-08-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_lahatra', '0008_guichet_nb_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='date_temps',
            field=models.CharField(default='', max_length=255),
        ),
    ]
