# Generated by Django 5.1 on 2024-08-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_lahatra', '0009_personne_date_temps'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='status',
            field=models.CharField(default='New', max_length=255),
        ),
    ]
