# Generated by Django 5.1 on 2024-08-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_lahatra', '0010_personne_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personne',
            old_name='status',
            new_name='statut',
        ),
    ]
