# Generated by Django 5.1.1 on 2024-09-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_lahatra', '0013_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='guichet',
            name='mdp_util',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='guichet',
            name='nom_util',
            field=models.CharField(default='', max_length=255),
        ),
    ]
